<a href="https://colab.research.google.com/github/gomigom1068/YBIGTA_DA/blob/main/Textmining_NLP_%EA%B8%B0%EC%82%AC%EB%B6%84%EC%84%9D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. 데이터 불러오기

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import numpy as np
from os import listdir
from os.path import isfile, join

mypath = '/content/drive/MyDrive/2021-2학기/텍스트마이닝/assignment1/docs/'
onlyfiles = [f for f in listdir(mypath) if isfile(join(mypath, f))]

total_docs = []
for file in onlyfiles:
    file_path = mypath+file
    with open(file_path, 'r', encoding='utf8') as f:
        content = f.read()
    total_docs.append(content)

In [ ]:
len(total_docs)

20

In [ ]:
total_docs[8]

'대장동 개발 특혜 의혹의 핵심 인물, 화천대유 대주주 김만배 씨의 구속 여부가 오늘(14일) 결정됩니다.\n\n검찰은 김 씨가 조사를 받은 지 하루 만에 구속영장을 청구했습니다.\n\n취재기자 연결합니다.\n\n신현정 기자, 검찰이 김만배 씨에게 적용한 혐의는 무엇입니까?\n\n[기자]\n\n네, 오늘(14일) 오전 10시 반부터 화천대유 대주주 김만배 씨에 대한 구속 전 피의자 심문이 시작됩니다.\n\n김 씨에게 적용된 혐의는 크게 세 가지입니다.\n\n뇌물 공여와 특정경제범죄 가중처벌법상 배임, 횡령인데요.\n\n검찰은 김 씨가 유동규 전 성남도시개발공사 본부장에게 지급하기로 약속한 700억 원과 실제로 건넨 5억 원을 비롯해, 화천대유에서 일한 곽상도 전 의원 아들이 퇴직금 명목으로 받은 50억 원을 뇌물로 봤습니다.\n\n검찰은 김 씨가 대장동 개발 사업으로 성남시에 최소 1,100억 원의 피해를 보게 한 것이 배임죄에 해당한다고 보고 있는데요.\n\n김 씨는 모든 혐의를 부인하고 있습니다.\n\n이른바 700억 약정설은 실체가 없으며, 곽상도 전 의원 아들에게 지급된 퇴직금 50억 원은 산재로 인한 금액으로, 정상적으로 처리된 것이라는 입장입니다.\n\n[앵커]\n\n법정에서 검찰과 김만배 씨의 주장이 팽팽하게 맞설 것으로 예상되는데, 관련 내용도 짚어주시죠.\n\n[기자]\n\n네, 검찰이 구속영장을 청구한 직후 김 씨는 변호인을 통해 강한 유감을 드러냈습니다.\n\n김씨는 천화동인 5호 소유주 정영학 회계사가 검찰에 제출한 녹취록을 신뢰할 수 없다고 주장해왔는데요.\n\n하지만 검찰이 이 녹취록을 영장 청구의 주된 근거로 삼았기 때문에 심각히 우려가 된다는 입장입니다.\n\n또 조사 과정에서 해당 녹취록을 제시하거나 들려주지 않아 피의자의 방어권이 침해당했다고도 밝혔습니다.\n\n변호인단은 이러한 점들을 토대로 법정에서 김 씨의 방어 논리를 제시할 계획입니다.\n\n반면 검찰은 앞서 유동규 전 본부장이 뇌물 혐의로 구속된 만큼, 김만배 씨 구속에

In [ ]:
!pip install konlpy

     |████████████████████████████████| 19.4 MB 1.3 MB/s 
     |████████████████████████████████| 86 kB 5.3 MB/s 
     |████████████████████████████████| 448 kB 73.5 MB/s 
  Attempting uninstall: beautifulsoup4
    Found existing installation: beautifulsoup4 4.6.3
    Uninstalling beautifulsoup4-4.6.3:
      Successfully uninstalled beautifulsoup4-4.6.3


In [ ]:
import konlpy.tag
import re

# 2-1 명사만 선택

In [ ]:
import konlpy.tag

def Kr_preprocessing_noun(text, customized_stopwords=None):
    filtered_content = re.sub(r'[^\s\d\w]','',text)
    twitter = konlpy.tag.Twitter()
    twitter_morphs = twitter.pos(filtered_content)
    Noun_words = []
    for word, pos in twitter_morphs:
        if pos == 'Noun':
            Noun_words.append(word)
    unique_Noun_words = set(Noun_words)
    for word in unique_Noun_words:
        if word in customized_stopwords or len(word)==1:
            while word in Noun_words: Noun_words.remove(word)
    return Noun_words

In [ ]:
stopwords = []
docs_nouns = [Kr_preprocessing_noun(doc,stopwords) for doc in total_docs]

/usr/local/lib/python3.7/dist-packages/konlpy/tag/_okt.py:16: UserWarning: "Twitter" has changed to "Okt" since KoNLPy v0.4.5.
  warn('"Twitter" has changed to "Okt" since KoNLPy v0.4.5.')


In [ ]:
print(docs_nouns[0]) # 첫번째 문서에 대한 내용 ((문서 내용, [명사단어])로 구성)

['글로벌', '온라인', '동영상', '서비스', '넷플릭스', '한국', '제작', '리지', '시리즈', '오징어', '게임', '투자', '대비', '이상', '경제', '이익', '주장', '국내', '제작사', '인센티브', '거의', '국회', '문화', '체육', '관광', '위원회', '소속', '김승수', '국민', '의원', '넷플릭스', '사가', '오징어', '게임', '투입', '제작비', '국내', '제작사', '금액', '정도', '의원', '반면', '넷플릭스', '사의', '시가총액', '지난', '미국', '나스닥', '종가', '기준', '기록', '오징어', '게임', '출시일', '동안', '가량', '증가', '투자', '대비', '넷플릭스', '사의', '경제', '이익', '추정', '설명', '의원', '넷플릭스', '해외', '유통', '판로', '확장', '차원', '도움', '해외', '저작권', '독점', '국내', '제작사', '하청', '기지', '전락', '우려', '지적', '오징어', '게임', '넷플릭스', '리지', '시리즈', '역대', '최대', '시청자', '기록', '세계', '인기', '넷플릭스', '저작권', '독점', '국내', '제작사', '직접', '인센티브', '해외', '저작권', '독점', '관련', '한국', '저작권', '위원회', '서면', '답변', '통해', '예상', '수익', '발생', '경우', '창작', '영상', '제작사', '플랫폼', '사업자', '합리', '배분', '제작사', '범위', '저작권', '확보', '지속', '성장', '위해', '방향', '한국', '콘텐츠', '진흥', '역시', '서면', '답변', '콘텐츠', '제작', '지원', '사업', '제작사', '지식', '재산권', '권리', '확보', '우위', '차지', '노력', '의원', '해외', '직접', '관련', '국내', '방송', '영화', '애니메이션', '영상', 

In [ ]:
from collections import Counter

for i in range(20) :
  c = Counter(docs_nouns[i])
  print(c)


Counter({'넷플릭스': 7, '제작사': 7, '국내': 5, '저작권': 5, '오징어': 4, '게임': 4, '의원': 4, '해외': 4, '한국': 3, '경제': 3, '독점': 3, '확보': 3, '콘텐츠': 3, '제작': 2, '리지': 2, '시리즈': 2, '투자': 2, '대비': 2, '이익': 2, '인센티브': 2, '위원회': 2, '사의': 2, '기록': 2, '직접': 2, '관련': 2, '서면': 2, '답변': 2, '영상': 2, '성장': 2, '지식': 2, '재산권': 2, '글로벌': 1, '온라인': 1, '동영상': 1, '서비스': 1, '이상': 1, '주장': 1, '거의': 1, '국회': 1, '문화': 1, '체육': 1, '관광': 1, '소속': 1, '김승수': 1, '국민': 1, '사가': 1, '투입': 1, '제작비': 1, '금액': 1, '정도': 1, '반면': 1, '시가총액': 1, '지난': 1, '미국': 1, '나스닥': 1, '종가': 1, '기준': 1, '출시일': 1, '동안': 1, '가량': 1, '증가': 1, '추정': 1, '설명': 1, '유통': 1, '판로': 1, '확장': 1, '차원': 1, '도움': 1, '하청': 1, '기지': 1, '전락': 1, '우려': 1, '지적': 1, '역대': 1, '최대': 1, '시청자': 1, '세계': 1, '인기': 1, '통해': 1, '예상': 1, '수익': 1, '발생': 1, '경우': 1, '창작': 1, '플랫폼': 1, '사업자': 1, '합리': 1, '배분': 1, '범위': 1, '지속': 1, '위해': 1, '방향': 1, '진흥': 1, '역시': 1, '지원': 1, '사업': 1, '권리': 1, '우위': 1, '차지': 1, '노력': 1, '방송': 1, '영화': 1, '애니메이션': 1, '대한민국': 1, '미래': 1, '먹거리': 1, '만큼': 1

In [ ]:
documents_filtered_noun = []
for doc in docs_nouns:
    document_filtered_noun =' '.join(doc)
    documents_filtered_noun.append(document_filtered_noun)
documents_filtered_noun

['글로벌 온라인 동영상 서비스 넷플릭스 한국 제작 리지 시리즈 오징어 게임 투자 대비 이상 경제 이익 주장 국내 제작사 인센티브 거의 국회 문화 체육 관광 위원회 소속 김승수 국민 의원 넷플릭스 사가 오징어 게임 투입 제작비 국내 제작사 금액 정도 의원 반면 넷플릭스 사의 시가총액 지난 미국 나스닥 종가 기준 기록 오징어 게임 출시일 동안 가량 증가 투자 대비 넷플릭스 사의 경제 이익 추정 설명 의원 넷플릭스 해외 유통 판로 확장 차원 도움 해외 저작권 독점 국내 제작사 하청 기지 전락 우려 지적 오징어 게임 넷플릭스 리지 시리즈 역대 최대 시청자 기록 세계 인기 넷플릭스 저작권 독점 국내 제작사 직접 인센티브 해외 저작권 독점 관련 한국 저작권 위원회 서면 답변 통해 예상 수익 발생 경우 창작 영상 제작사 플랫폼 사업자 합리 배분 제작사 범위 저작권 확보 지속 성장 위해 방향 한국 콘텐츠 진흥 역시 서면 답변 콘텐츠 제작 지원 사업 제작사 지식 재산권 권리 확보 우위 차지 노력 의원 해외 직접 관련 국내 방송 영화 애니메이션 영상 콘텐츠 대한민국 경제 성장 미래 먹거리 만큼 지식 재산권 확보 매우 과제 강조',
 '글로벌 온라인 동영상 서비스 넷플릭스 오징어 게임 투자 대비 이상 경제 이익 주장 제기 국회 문화 체육 관광 위원회 소속 김승수 국민 의원 국정감사 자료 넷플릭스 제작비 투입 오징어 게임 공개 시가총액 미국 나스닥 종가 기준 가량 증가 의원 투자 대비 넷플릭스 경제 이익 추정 제작사 수입 넷플릭스 저작권 독점 흥행 이후 국내 제작사 직접 인센티브 지적 넷플릭스 해외 온라인 동영상 서비스 국내 콘텐츠 판로 확장 차원 도움 저작권 독점 국내 제작사 해외 하청 기지 전락 우려 정부 차원 대책 촉구 관련 한국 저작권 위원회 서면 답변 통해 예상 수익 발생 경우 창작 영상 제작사 플랫폼 사업자 합리 배분 제작사 범위 저작권 확보 지속 성장 위해 한국 콘텐츠 진흥 답변서 콘텐츠 제작 지원 사업 제작사 지적재산권 권리 확보 우위 차지 노력 의원 넷플릭스 국내

# 2-2 TF 정보를 이용하여 벡터화하기

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer # frequency based DTM
def tf_extractor(corpus): 
    # returns a frequency-based DTM
    vectorizer = CountVectorizer(min_df=1, ngram_range=(1,1))
    features = vectorizer.fit_transform(corpus) # transform texts to a frequency matrix
    return vectorizer, features 

vectorizer_tf, DTM_tf_noun = tf_extractor(documents_filtered_noun) # 문서들을 TF matrix로 변환 
DTM_TF_noun = np.array(DTM_tf_noun.todense())

In [ ]:
DTM_TF_noun

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [1, 1, 0, ..., 0, 0, 0],
       [2, 1, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0]])

**실루엣 스코어를 이용한 최적의 군집 수 구하기**

In [ ]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
for k in range(2,10):
    kmeans = KMeans(n_clusters=k, max_iter=10, random_state = 40)
    cluster = kmeans.fit_predict(DTM_TF_noun) 
    print(k, silhouette_score(DTM_TF_noun, cluster))

2 0.40623064396885084
3 0.4373456367042235
4 0.5621436855009254
5 0.5069856609574241
6 0.4024825682770256
7 0.4601741108142816
8 0.3713408044423826
9 0.3727472782162194


In [ ]:
#silhouette score가 가장 높은 k : 4
#따라서 최적의 군집 수는 4개
kmeans = KMeans(n_clusters=4,max_iter=10, random_state = 40)
clusters_TF_noun = kmeans.fit_predict(DTM_TF_noun)
print(clusters_TF_noun)

[2 2 2 2 2 0 0 0 0 0 0 3 3 3 1 1 1 1 1 1]


In [ ]:
import pandas as pd

In [ ]:
pd.DataFrame({'clustering label' : kmeans.fit_predict(DTM_TF_noun), 'corpus' : documents_filtered_noun})

clustering label                                             corpus
0                  2  글로벌 온라인 동영상 서비스 넷플릭스 한국 제작 리지 시리즈 오징어 게임 투자 대비...
1                  2  글로벌 온라인 동영상 서비스 넷플릭스 오징어 게임 투자 대비 이상 경제 이익 주장 ...
2                  2  글로벌 온라인 동영상 서비스 넷플릭스 오징어 게임 흥행 투자 대비 이상 경제 이익 ...
3                  2  넷플릭스 오징어 게임 이상 이익 주장 제기 국회 문화 체육 관광 위원회 소속 김승수...
4                  2  전세계 인기 오징어 게임 넷플릭스 이상 경제 이익 주장 제기 국회 문화 체육 관광 ...
5                  0  대장동 개발 로비 특혜 의혹 핵심 인물 화천 대유 자산 관리 화천 대유 주주 만배 ...
6                  0  대장동 개발 로비 특혜 의혹 핵심 인물 화천 대유 자산 관리 화천 대유 주주 만배 ...
7                  0  경기 성남시 대장동 개발 사업 핵심 인물 화천 대유 자산 관리 화천 대유 주주 김만...
8                  0  대장동 개발 특혜 의혹 핵심 인물 화천 대유 주주 만배 구속 여부 오늘 결정 검찰 ...
9                  0  대장동 개발 특혜 의혹 핵심 인물 화천 대유 자산 관리 주주 김만 배씨 구속 여부 ...
10                 0  대장동 개발 사업 특혜 의혹 핵심 인물 화천 대유 주주 만배 구속 여부 오늘 결정 ...
11                 3  연속 월드컵 본선 진출 도전 한국 축구 이란 원정 손흥민 토트넘 선제골 파울루 감독...
12                 3  연속 월드컵 본선 진출 도전 한국 축구 이란 원정 무승부 파울루 감독 지휘 한국 축...
13                 3  한국 축구 이란 원정 손흥민 토트넘 선제골 파울루 감독 지휘 한국 축구 대표팀 오후...
14                 1  금융 당국 대출 관리 한도 규제 예외 인정 다음주 은행 전세 대출 재개 대출 한도 ...
15                 1  주요 시중 은행 전세 신규 대출 재개 금융 당국 서민 실수 보호 위해 대출 올해 관...
16                 1  금융 당국 가계부채 연간 증가 목표 대출 제외 결정 농협 은행 중단 전세 대출 판매...
17                 1  금융 당국 대출 관리 한도 규제 예외 인정 다음주 은행 전세 대출 재개 대출 한도 ...
18                 1  일부 은행 전세 대출 제한 전망 금융 감독 당국 가계부채 총량 관리 대출 제외 조치...
19                 1  금융 당국 대출 관리 한도 규제 예외 인정 다음 시중 은행 전세 대출 재개 대출 한...

# 2-3 TF-IDF 정보를 이용하여 벡터화하기

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer # tf-idf based DTM

def tfidf_extractor(corpus):
    # returns a tf-idf based DTM
    vectorizer = TfidfVectorizer()
    features = vectorizer.fit_transform(corpus)
    return vectorizer, features
    #features에 DTM 정보(vectorazation 된 정보)가 저장되어 있음

vectorizer_tfidf, DTM_tfidf_noun = tfidf_extractor(documents_filtered_noun) 
DTM_TFIDF_noun = np.array(DTM_tfidf_noun.todense())

**실루엣 스코어를 이용한 최적의 군집 수 구하기**

In [ ]:
for k in range(2,10):
    kmeans = KMeans(n_clusters=k, max_iter=10, random_state = 40)
    cluster = kmeans.fit_predict(DTM_TFIDF_noun) 
    print(k, silhouette_score(DTM_TFIDF_noun, cluster))

2 0.3031848812262737
3 0.42115692609668737
4 0.566846835490535
5 0.5003877595483472
6 0.48736396041266544
7 0.41201385552837816
8 0.4037591944429127
9 0.41696497134683386


In [ ]:
#silhouette score가 가장 높은 k : 4
#따라서 최적의 군집 수는 4개
kmeans = KMeans(n_clusters=4, max_iter=10, random_state = 40)
print(kmeans.fit_predict(DTM_TFIDF_noun))

[2 2 2 2 2 0 0 0 0 0 0 3 3 3 1 1 1 1 1 1]


In [ ]:
pd.DataFrame({'clustering label' : kmeans.fit_predict(DTM_TFIDF_noun), 'corpus' : documents_filtered_noun})

clustering label                                             corpus
0                  2  글로벌 온라인 동영상 서비스 넷플릭스 한국 제작 리지 시리즈 오징어 게임 투자 대비...
1                  2  글로벌 온라인 동영상 서비스 넷플릭스 오징어 게임 투자 대비 이상 경제 이익 주장 ...
2                  2  글로벌 온라인 동영상 서비스 넷플릭스 오징어 게임 흥행 투자 대비 이상 경제 이익 ...
3                  2  넷플릭스 오징어 게임 이상 이익 주장 제기 국회 문화 체육 관광 위원회 소속 김승수...
4                  2  전세계 인기 오징어 게임 넷플릭스 이상 경제 이익 주장 제기 국회 문화 체육 관광 ...
5                  0  대장동 개발 로비 특혜 의혹 핵심 인물 화천 대유 자산 관리 화천 대유 주주 만배 ...
6                  0  대장동 개발 로비 특혜 의혹 핵심 인물 화천 대유 자산 관리 화천 대유 주주 만배 ...
7                  0  경기 성남시 대장동 개발 사업 핵심 인물 화천 대유 자산 관리 화천 대유 주주 김만...
8                  0  대장동 개발 특혜 의혹 핵심 인물 화천 대유 주주 만배 구속 여부 오늘 결정 검찰 ...
9                  0  대장동 개발 특혜 의혹 핵심 인물 화천 대유 자산 관리 주주 김만 배씨 구속 여부 ...
10                 0  대장동 개발 사업 특혜 의혹 핵심 인물 화천 대유 주주 만배 구속 여부 오늘 결정 ...
11                 3  연속 월드컵 본선 진출 도전 한국 축구 이란 원정 손흥민 토트넘 선제골 파울루 감독...
12                 3  연속 월드컵 본선 진출 도전 한국 축구 이란 원정 무승부 파울루 감독 지휘 한국 축...
13                 3  한국 축구 이란 원정 손흥민 토트넘 선제골 파울루 감독 지휘 한국 축구 대표팀 오후...
14                 1  금융 당국 대출 관리 한도 규제 예외 인정 다음주 은행 전세 대출 재개 대출 한도 ...
15                 1  주요 시중 은행 전세 신규 대출 재개 금융 당국 서민 실수 보호 위해 대출 올해 관...
16                 1  금융 당국 가계부채 연간 증가 목표 대출 제외 결정 농협 은행 중단 전세 대출 판매...
17                 1  금융 당국 대출 관리 한도 규제 예외 인정 다음주 은행 전세 대출 재개 대출 한도 ...
18                 1  일부 은행 전세 대출 제한 전망 금융 감독 당국 가계부채 총량 관리 대출 제외 조치...
19                 1  금융 당국 대출 관리 한도 규제 예외 인정 다음 시중 은행 전세 대출 재개 대출 한...

# 3.1 명사와 동사 선택

In [ ]:
def Kr_preprocessing_noun_verb(text, customized_stopwords=None):
    filtered_content = re.sub(r'[^\s\d\w]','',text)
    twitter = konlpy.tag.Twitter()
    twitter_morphs = twitter.pos(filtered_content)
    Noun_Verb_words = []
    for word, pos in twitter_morphs:
        if pos == 'Noun' or pos == 'Verb' :
            Noun_Verb_words.append(word)
    unique_Noun_Verb_words = set(Noun_Verb_words)
    for word in unique_Noun_Verb_words:
        if word in customized_stopwords or len(word)==1:
            while word in Noun_Verb_words: Noun_Verb_words.remove(word)
    return Noun_Verb_words

In [ ]:
stopwords = []
docs_nouns_verbs = [Kr_preprocessing_noun_verb(doc,stopwords) for doc in total_docs]

/usr/local/lib/python3.7/dist-packages/konlpy/tag/_okt.py:16: UserWarning: "Twitter" has changed to "Okt" since KoNLPy v0.4.5.
  warn('"Twitter" has changed to "Okt" since KoNLPy v0.4.5.')


In [ ]:
from collections import Counter

for i in range(20) :
  c = Counter(docs_nouns_verbs[i])
  print(c)

Counter({'넷플릭스': 7, '제작사': 7, '국내': 5, '했다': 5, '저작권': 5, '오징어': 4, '게임': 4, '의원': 4, '해외': 4, '한국': 3, '경제': 3, '독점': 3, '확보': 3, '콘텐츠': 3, '제작': 2, '리지': 2, '시리즈': 2, '투자': 2, '대비': 2, '이익': 2, '돌아가는': 2, '인센티브': 2, '위원회': 2, '밝혔다': 2, '사의': 2, '기록': 2, '하는': 2, '직접': 2, '관련': 2, '서면': 2, '답변': 2, '영상': 2, '성장': 2, '지식': 2, '재산권': 2, '글로벌': 1, '온라인': 1, '동영상': 1, '서비스': 1, '이상': 1, '가져갔다는': 1, '주장': 1, '나왔다': 1, '거의': 1, '알려졌다': 1, '국회': 1, '문화': 1, '체육': 1, '관광': 1, '소속': 1, '김승수': 1, '국민': 1, '사가': 1, '투입': 1, '제작비': 1, '받게': 1, '금액': 1, '정도': 1, '반면': 1, '시가총액': 1, '지난': 1, '미국': 1, '나스닥': 1, '종가': 1, '기준': 1, '하면서': 1, '출시일': 1, '동안': 1, '가량': 1, '증가': 1, '추정': 1, '된다고': 1, '설명': 1, '유통': 1, '판로': 1, '확장': 1, '차원': 1, '도움': 1, '들이': 1, '하면': 1, '하청': 1, '기지': 1, '전락': 1, '우려': 1, '지적': 1, '역대': 1, '최대': 1, '시청자': 1, '세계': 1, '인기': 1, '통해': 1, '예상': 1, '넘는': 1, '수익': 1, '발생': 1, '경우': 1, '창작': 1, '플랫폼': 1, '사업자': 1, '합리': 1, '배분': 1, '이루어질': 1, '범위': 1, '하도록': 1, '지속': 1, '위해': 1,

In [ ]:
#불용어 제거
stopwords=['했다','했습니다','하는','하며']
docs_nouns_verbs = [Kr_preprocessing_noun_verb(doc,stopwords) for doc in total_docs]
for i in range(20) :
  c = Counter(docs_nouns_verbs[i])
  print(c)

/usr/local/lib/python3.7/dist-packages/konlpy/tag/_okt.py:16: UserWarning: "Twitter" has changed to "Okt" since KoNLPy v0.4.5.
  warn('"Twitter" has changed to "Okt" since KoNLPy v0.4.5.')


Counter({'넷플릭스': 7, '제작사': 7, '국내': 5, '저작권': 5, '오징어': 4, '게임': 4, '의원': 4, '해외': 4, '한국': 3, '경제': 3, '독점': 3, '확보': 3, '콘텐츠': 3, '제작': 2, '리지': 2, '시리즈': 2, '투자': 2, '대비': 2, '이익': 2, '돌아가는': 2, '인센티브': 2, '위원회': 2, '밝혔다': 2, '사의': 2, '기록': 2, '직접': 2, '관련': 2, '서면': 2, '답변': 2, '영상': 2, '성장': 2, '지식': 2, '재산권': 2, '글로벌': 1, '온라인': 1, '동영상': 1, '서비스': 1, '이상': 1, '가져갔다는': 1, '주장': 1, '나왔다': 1, '거의': 1, '알려졌다': 1, '국회': 1, '문화': 1, '체육': 1, '관광': 1, '소속': 1, '김승수': 1, '국민': 1, '사가': 1, '투입': 1, '제작비': 1, '받게': 1, '금액': 1, '정도': 1, '반면': 1, '시가총액': 1, '지난': 1, '미국': 1, '나스닥': 1, '종가': 1, '기준': 1, '하면서': 1, '출시일': 1, '동안': 1, '가량': 1, '증가': 1, '추정': 1, '된다고': 1, '설명': 1, '유통': 1, '판로': 1, '확장': 1, '차원': 1, '도움': 1, '들이': 1, '하면': 1, '하청': 1, '기지': 1, '전락': 1, '우려': 1, '지적': 1, '역대': 1, '최대': 1, '시청자': 1, '세계': 1, '인기': 1, '통해': 1, '예상': 1, '넘는': 1, '수익': 1, '발생': 1, '경우': 1, '창작': 1, '플랫폼': 1, '사업자': 1, '합리': 1, '배분': 1, '이루어질': 1, '범위': 1, '하도록': 1, '지속': 1, '위해': 1, '방향': 1, '진흥': 1,

In [ ]:
documents_filtered_noun_verb = []
for doc in docs_nouns_verbs:
    document_filtered_noun_verb =' '.join(doc)
    documents_filtered_noun_verb.append(document_filtered_noun_verb)
documents_filtered_noun_verb[0]

'글로벌 온라인 동영상 서비스 넷플릭스 한국 제작 리지 시리즈 오징어 게임 투자 대비 이상 경제 이익 가져갔다는 주장 나왔다 국내 제작사 돌아가는 인센티브 거의 알려졌다 국회 문화 체육 관광 위원회 소속 김승수 국민 의원 넷플릭스 사가 오징어 게임 투입 제작비 국내 제작사 받게 금액 정도 밝혔다 의원 반면 넷플릭스 사의 시가총액 지난 미국 나스닥 종가 기준 기록 하면서 오징어 게임 출시일 동안 가량 증가 투자 대비 넷플릭스 사의 경제 이익 추정 된다고 설명 의원 넷플릭스 해외 유통 판로 확장 차원 도움 해외 들이 저작권 독점 하면 국내 제작사 하청 기지 전락 우려 지적 오징어 게임 넷플릭스 리지 시리즈 역대 최대 시청자 기록 세계 인기 넷플릭스 저작권 독점 국내 제작사 돌아가는 직접 인센티브 해외 저작권 독점 관련 한국 저작권 위원회 서면 답변 통해 예상 넘는 수익 발생 경우 창작 영상 제작사 플랫폼 사업자 합리 배분 이루어질 제작사 범위 저작권 확보 하도록 지속 성장 위해 방향 밝혔다 한국 콘텐츠 진흥 역시 서면 답변 콘텐츠 제작 지원 사업 제작사 지식 재산권 권리 확보 우위 차지 노력 기울이겠다고 의원 해외 직접 관련 국내 방송 영화 애니메이션 영상 콘텐츠 대한민국 경제 성장 시킬 미래 먹거리 만큼 지식 재산권 확보 매우 과제 강조'

In [ ]:
documents_filtered_noun_verb

['글로벌 온라인 동영상 서비스 넷플릭스 한국 제작 리지 시리즈 오징어 게임 투자 대비 이상 경제 이익 가져갔다는 주장 나왔다 국내 제작사 돌아가는 인센티브 거의 알려졌다 국회 문화 체육 관광 위원회 소속 김승수 국민 의원 넷플릭스 사가 오징어 게임 투입 제작비 국내 제작사 받게 금액 정도 밝혔다 의원 반면 넷플릭스 사의 시가총액 지난 미국 나스닥 종가 기준 기록 하면서 오징어 게임 출시일 동안 가량 증가 투자 대비 넷플릭스 사의 경제 이익 추정 된다고 설명 의원 넷플릭스 해외 유통 판로 확장 차원 도움 해외 들이 저작권 독점 하면 국내 제작사 하청 기지 전락 우려 지적 오징어 게임 넷플릭스 리지 시리즈 역대 최대 시청자 기록 세계 인기 넷플릭스 저작권 독점 국내 제작사 돌아가는 직접 인센티브 해외 저작권 독점 관련 한국 저작권 위원회 서면 답변 통해 예상 넘는 수익 발생 경우 창작 영상 제작사 플랫폼 사업자 합리 배분 이루어질 제작사 범위 저작권 확보 하도록 지속 성장 위해 방향 밝혔다 한국 콘텐츠 진흥 역시 서면 답변 콘텐츠 제작 지원 사업 제작사 지식 재산권 권리 확보 우위 차지 노력 기울이겠다고 의원 해외 직접 관련 국내 방송 영화 애니메이션 영상 콘텐츠 대한민국 경제 성장 시킬 미래 먹거리 만큼 지식 재산권 확보 매우 과제 강조',
 '글로벌 온라인 동영상 서비스 넷플릭스 오징어 게임 투자 대비 이상 경제 이익 누렸다는 주장 제기 됐다 국회 문화 체육 관광 위원회 소속 김승수 국민 의원 국정감사 자료 따르면 넷플릭스 제작비 투입 오징어 게임 공개 시가총액 미국 나스닥 종가 기준 가량 증가 의원 투자 대비 넷플릭스 경제 이익 추정 되는 제작사 돌아가는 수입 넷플릭스 저작권 독점 흥행 이후 국내 제작사 직접 인센티브 지적 이어 넷플릭스 해외 온라인 동영상 서비스 국내 콘텐츠 판로 확장 차원 도움 되지만 저작권 독점 국내 제작사 해외 하청 기지 전락 우려 크다며 정부 차원 대책 촉구 관련 한국 저작권 위원회 서면 답변 통해 예상 넘는 수익 발생 경우 창작 

# 3-2 TF 정보를 이용하여 벡터화하기

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer # frequency based DTM
def tf_extractor(corpus): 
    # returns a frequency-based DTM
    vectorizer = CountVectorizer(min_df=1, ngram_range=(1,1))
    features = vectorizer.fit_transform(corpus) # transform texts to a frequency matrix
    return vectorizer, features 

vectorizer_tf_verb, DTM_tf_noun_verb = tf_extractor(documents_filtered_noun_verb) # 문서들을 TF matrix로 변환 
DTM_TF_noun_verb = np.array(DTM_tf_noun_verb.todense())

**실루엣 스코어를 이용한 최적의 군집 수 구하기**

In [ ]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
for k in range(2,10):
    kmeans = KMeans(n_clusters=k, max_iter=10, random_state = 40)
    cluster = kmeans.fit_predict(DTM_TF_noun_verb) 
    print(k, silhouette_score(DTM_TF_noun_verb, cluster))

2 0.39331367191070193
3 0.41823155048981525
4 0.5365264052428957
5 0.4887186711137942
6 0.4678207394007659
7 0.4586523682887676
8 0.34349189069661656
9 0.36046096263414984


In [ ]:
#silhouette score가 가장 높은 k : 4
#따라서 최적의 군집 수는 4개
kmeans = KMeans(n_clusters=4, max_iter=10, random_state = 40)
print(kmeans.fit_predict(DTM_TF_noun_verb))

[2 2 2 2 2 0 0 0 0 0 0 3 3 3 1 1 1 1 1 1]


In [ ]:
pd.DataFrame({'clustering label' : kmeans.fit_predict(DTM_TF_noun_verb), 'corpus' : documents_filtered_noun_verb})

clustering label                                             corpus
0                  2  글로벌 온라인 동영상 서비스 넷플릭스 한국 제작 리지 시리즈 오징어 게임 투자 대비...
1                  2  글로벌 온라인 동영상 서비스 넷플릭스 오징어 게임 투자 대비 이상 경제 이익 누렸다...
2                  2  글로벌 온라인 동영상 서비스 넷플릭스 오징어 게임 흥행 투자 대비 이상 경제 이익 ...
3                  2  넷플릭스 오징어 게임 이상 이익 냈다는 주장 제기 됐다 국회 문화 체육 관광 위원회...
4                  2  전세계 인기 얻고 오징어 게임 넷플릭스 이상 경제 이익 누렸다는 주장 제기 됐다 국...
5                  0  대장동 개발 로비 특혜 의혹 핵심 인물 화천 대유 자산 관리 화천 대유 주주 만배 ...
6                  0  대장동 개발 로비 특혜 의혹 핵심 인물 화천 대유 자산 관리 화천 대유 주주 만배 ...
7                  0  경기 성남시 대장동 개발 사업 핵심 인물 화천 대유 자산 관리 화천 대유 주주 김만...
8                  0  대장동 개발 특혜 의혹 핵심 인물 화천 대유 주주 만배 구속 여부 오늘 결정 됩니다...
9                  0  대장동 개발 특혜 의혹 핵심 인물 화천 대유 자산 관리 주주 김만 배씨 구속 여부 ...
10                 0  대장동 개발 사업 특혜 의혹 핵심 인물 화천 대유 주주 만배 구속 여부 이르면 오늘...
11                 3  연속 월드컵 본선 진출 도전 한국 축구 이란 원정 손흥민 토트넘 선제골 지키지 비겼...
12                 3  연속 월드컵 본선 진출 도전 한국 축구 이란 원정 무승부 거뒀다 파울루 감독 지휘 ...
13                 3  한국 축구 이란 원정 손흥민 토트넘 선제골 지키지 비겼다 파울루 감독 지휘 한국 축...
14                 1  금융 당국 대출 관리 한도 규제 예외 인정 하기로 하면서 다음주 은행 전세 대출 재...
15                 1  주요 시중 은행 전세 신규 대출 재개 한다고 밝혔다 금융 당국 서민 실수 보호 위해...
16                 1  금융 당국 가계부채 연간 증가 목표 대출 제외 하기로 결정 하면서 농협 은행 중단 ...
17                 1  금융 당국 대출 관리 한도 규제 예외 인정 하기로 하면서 다음주 은행 전세 대출 재...
18                 1  일부 은행 막혔던 전세 대출 제한 들이 풀릴 전망 금융 감독 당국 가계부채 총량 관...
19                 1  금융 당국 대출 관리 한도 규제 예외 인정 하기로 하면서 다음 시중 은행 전세 대출...

# 3-3 TF-IDF 정보를 이용하여 벡터화하기

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer # tf-idf based DTM

def tfidf_extractor(corpus):
    # returns a tf-idf based DTM
    vectorizer = TfidfVectorizer()
    features = vectorizer.fit_transform(corpus)
    return vectorizer, features
    #features에 DTM 정보(vectorazation 된 정보)가 저장되어 있음

vectorizer_tfidf, DTM_tfidf_noun_verb = tfidf_extractor(documents_filtered_noun_verb) 
DTM_TFIDF_noun_verb = np.array(DTM_tfidf_noun_verb.todense())

**실루엣 스코어를 이용한 최적의 군집 수 구하기**

In [ ]:
for k in range(2,10):
    kmeans = KMeans(n_clusters=k, max_iter=10, random_state = 40)
    cluster = kmeans.fit_predict(DTM_TFIDF_noun_verb) 
    print(k, silhouette_score(DTM_TFIDF_noun_verb, cluster))

2 0.2875719123638671
3 0.3973450210987237
4 0.5380778690623369
5 0.4785676488505753
6 0.4615103022908231
7 0.39912677111292166
8 0.4020846249773086
9 0.4001362464417061


In [ ]:
#silhouette score가 가장 높은 k : 4
#따라서 최적의 군집 수는 4개
kmeans = KMeans(n_clusters=4, max_iter=10, random_state = 40)
print(kmeans.fit_predict(DTM_TFIDF_noun_verb))

[2 2 2 2 2 0 0 0 0 0 0 3 3 3 1 1 1 1 1 1]


In [ ]:
pd.DataFrame({'clustering label' : kmeans.fit_predict(DTM_TFIDF_noun_verb), 
              'corpus' : documents_filtered_noun_verb})

clustering label                                             corpus
0                  2  글로벌 온라인 동영상 서비스 넷플릭스 한국 제작 리지 시리즈 오징어 게임 투자 대비...
1                  2  글로벌 온라인 동영상 서비스 넷플릭스 오징어 게임 투자 대비 이상 경제 이익 누렸다...
2                  2  글로벌 온라인 동영상 서비스 넷플릭스 오징어 게임 흥행 투자 대비 이상 경제 이익 ...
3                  2  넷플릭스 오징어 게임 이상 이익 냈다는 주장 제기 됐다 국회 문화 체육 관광 위원회...
4                  2  전세계 인기 얻고 오징어 게임 넷플릭스 이상 경제 이익 누렸다는 주장 제기 됐다 국...
5                  0  대장동 개발 로비 특혜 의혹 핵심 인물 화천 대유 자산 관리 화천 대유 주주 만배 ...
6                  0  대장동 개발 로비 특혜 의혹 핵심 인물 화천 대유 자산 관리 화천 대유 주주 만배 ...
7                  0  경기 성남시 대장동 개발 사업 핵심 인물 화천 대유 자산 관리 화천 대유 주주 김만...
8                  0  대장동 개발 특혜 의혹 핵심 인물 화천 대유 주주 만배 구속 여부 오늘 결정 됩니다...
9                  0  대장동 개발 특혜 의혹 핵심 인물 화천 대유 자산 관리 주주 김만 배씨 구속 여부 ...
10                 0  대장동 개발 사업 특혜 의혹 핵심 인물 화천 대유 주주 만배 구속 여부 이르면 오늘...
11                 3  연속 월드컵 본선 진출 도전 한국 축구 이란 원정 손흥민 토트넘 선제골 지키지 비겼...
12                 3  연속 월드컵 본선 진출 도전 한국 축구 이란 원정 무승부 거뒀다 파울루 감독 지휘 ...
13                 3  한국 축구 이란 원정 손흥민 토트넘 선제골 지키지 비겼다 파울루 감독 지휘 한국 축...
14                 1  금융 당국 대출 관리 한도 규제 예외 인정 하기로 하면서 다음주 은행 전세 대출 재...
15                 1  주요 시중 은행 전세 신규 대출 재개 한다고 밝혔다 금융 당국 서민 실수 보호 위해...
16                 1  금융 당국 가계부채 연간 증가 목표 대출 제외 하기로 결정 하면서 농협 은행 중단 ...
17                 1  금융 당국 대출 관리 한도 규제 예외 인정 하기로 하면서 다음주 은행 전세 대출 재...
18                 1  일부 은행 막혔던 전세 대출 제한 들이 풀릴 전망 금융 감독 당국 가계부채 총량 관...
19                 1  금융 당국 대출 관리 한도 규제 예외 인정 하기로 하면서 다음 시중 은행 전세 대출...

In [ ]:
import pandas as pd

In [ ]:
kmeans = KMeans(n_clusters=4, max_iter=10, random_state = 40)
df = pd.DataFrame([
              ['TF+명사만',silhouette_score(DTM_TF_noun, kmeans.fit_predict(DTM_TF_noun))],
              ['TF+명사동사',silhouette_score(DTM_TF_noun_verb, kmeans.fit_predict(DTM_TF_noun_verb))],
              ['TFIDF+명사만',silhouette_score(DTM_TFIDF_noun, kmeans.fit_predict(DTM_TFIDF_noun))],
              ['TFIDF+명사동사',silhouette_score(DTM_TFIDF_noun_verb, kmeans.fit_predict(DTM_TFIDF_noun_verb))]
              ], columns=['분석방법','실루엣 스코어'])

#실루엣 스코어를 기준으로 내림차순 정렬
df.sort_values(by=['실루엣 스코어'],ascending=False)

분석방법   실루엣 스코어
2   TFIDF+명사만  0.566847
0      TF+명사만  0.562144
3  TFIDF+명사동사  0.538078
1     TF+명사동사  0.536526

In [ ]:
print('TF+명사만',kmeans.fit_predict(DTM_TF_noun))
print('TF+명사동사',kmeans.fit_predict(DTM_TF_noun_verb))
print('TFIDF+명사만',kmeans.fit_predict(DTM_TFIDF_noun))
print('TFIDF+명사동사',kmeans.fit_predict(DTM_TFIDF_noun_verb))

TF+명사만 [2 2 2 2 2 0 0 0 0 0 0 3 3 3 1 1 1 1 1 1]
TF+명사동사 [2 2 2 2 2 0 0 0 0 0 0 3 3 3 1 1 1 1 1 1]
TFIDF+명사만 [2 2 2 2 2 0 0 0 0 0 0 3 3 3 1 1 1 1 1 1]
TFIDF+명사동사 [2 2 2 2 2 0 0 0 0 0 0 3 3 3 1 1 1 1 1 1]
